[versions]

java = "VERSION_1_8"

# Build constants
minSdk = "26"
compileSdk = "34"
targetSdk = "33"

# Detekt
detekt = "1.23.3"
detektTwitterComposeRules ="0.0.26"
org-jetbrains-kotlin-android = "1.9.0"
legacy-support-v4 = "1.0.0"
lifecycle-livedata-ktx = "2.6.2"
lifecycle-viewmodel-ktx = "2.6.2"

[libraries]

# Detekt
staticAnalysis-detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
staticAnalysis-detektCli = { module = "io.gitlab.arturbosch.detekt:detekt-cli", version.ref = "detekt" }
staticAnalysis-detektApi = { module = "io.gitlab.arturbosch.detekt:detekt-api", version.ref = "detekt" }
staticAnalysis-detektTest = { module = "io.gitlab.arturbosch.detekt:detekt-test", version.ref = "detekt" }
staticAnalysis-detektFormatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
staticAnalysis-detektLibraries = { module = "io.gitlab.arturbosch.detekt:detekt-rules-libraries", version.ref = "detekt" }
staticAnalysis-detektTwitterComposeRules = { module = "com.twitter.compose.rules:detekt", version.ref = "detektTwitterComposeRules" }

# AndroidX
androidX-core = "androidx.core:core-ktx:1.12.0"
androidX-appCompat = "androidx.appcompat:appcompat:1.6.1"

# UI layer libraries
ui-material = "com.google.android.material:material:1.10.0"
ui-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.4"

# Unit tests
unitTests-junit = "junit:junit:4.13.2"

# UI tests
uiTests-junitExt = "androidx.test.ext:junit:1.1.5"
uiTests-espressoCore = "androidx.test.espresso:espresso-core:3.5.1"

# Room
room-runtime = "androidx.room:room-runtime:2.6.0"
room-ktx = "androidx.room:room-ktx:2.6.0"
room-compiler = "androidx.room:room-compiler:2.6.0"

# Retrofit
retrofit-converterGson = "com.squareup.retrofit2:converter-gson:2.9.0"
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"

# Glide
glide = "com.github.bumptech.glide:glide:4.15.1"
glide-compiler = "com.github.bumptech.glide:compiler:4.15.1"

# Fragments
fragments-navigationFragment = "androidx.navigation:navigation-fragment-ktx:2.7.5"
fragments-navigationUi = "androidx.navigation:navigation-ui-ktx:2.7.5"
fragments-fragmentKtx = "androidx.fragment:fragment-ktx:1.6.2"

# Hilt
hilt = "com.google.dagger:hilt-android:2.44"
hilt-compiler = "com.google.dagger:hilt-android-compiler:2.44"

# LeakCanary
leakCanary = "com.squareup.leakcanary:leakcanary-android:2.12"
legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacy-support-v4" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle-livedata-ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }

[bundles]
[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
